#SMTP SERVER CONFIGURATION
SMTP_SERVER = "mail.unity.com"
SMTP_USER = "alerts@uniti.com"
SMTP_PASSWORD = 'password123"

#EMAIL RECIPIENTS
EMAIL_RECIPIENTS = "sb2233@jagmail.southalabama.edu"

#ALERT THRESHOLDS

ALERT_ON_CRITICAL = True
ALERT_ON_HIGH_COUNT = 10
ALERT_ON_NEW_DEVICES = True
