{
 "title": "Vulnerability Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1h",
 "templating": {
  "list": [
   {
    "name": "CVE_Filter",
    "label": "CVE",
    "query": "SELECT DISTINCT cve_id\nFROM vulnerabilities\nWHERE cve_id != 'Unknown'"
   },
   {
    "name": "Host_Filter",
    "label": "Hosts",
    "query": "SELECT DISTINCT host\nFROM vulnerabilities"
   },
   { "name": "Risk_Filter", "label": "Risk", "query": "Critical, High, Medium, Low" }
  ]
 },
 "panels": [
  {
   "title": "Total Vulnerabilites",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT COUNT(DISTINCT cve_id) as total_CVEs \nFROM vulnerabilities\nWHERE ('$CVE_Filter' = 'All' or cve_id IN (${CVE_Filter:sqlstring})) \nAND\n('$Host_Filter' = 'All' or host IN (${Host_Filter:sqlstring}))\nAND\n('$Risk_Filter' = 'All' or risk IN (${Risk_Filter:sqlstring}))",
     "rawQueryText": "SELECT COUNT(DISTINCT cve_id) as total_CVEs \nFROM vulnerabilities\nWHERE ('$CVE_Filter' = 'All' or cve_id IN (${CVE_Filter:sqlstring})) \nAND\n('$Host_Filter' = 'All' or host IN (${Host_Filter:sqlstring}))\nAND\n('$Risk_Filter' = 'All' or risk IN (${Risk_Filter:sqlstring}))",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Total hosts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT COUNT(DISTINCT Host) as total_hosts \nFROM vulnerabilities\nWHERE ('$CVE_Filter' = 'All' or cve_id IN (${CVE_Filter:sqlstring})) \nAND\n('$Host_Filter' = 'All' or host IN (${Host_Filter:sqlstring}))\nAND\n('$Risk_Filter' = 'All' or risk IN (${Risk_Filter:sqlstring}))",
     "rawQueryText": "SELECT COUNT(DISTINCT Host) as total_hosts \nFROM vulnerabilities\nWHERE ('$CVE_Filter' = 'All' or cve_id IN (${CVE_Filter:sqlstring})) \nAND\n('$Host_Filter' = 'All' or host IN (${Host_Filter:sqlstring}))\nAND\n('$Risk_Filter' = 'All' or risk IN (${Risk_Filter:sqlstring}))",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "NAME ME",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "queryText": "SELECT cve_id, host, risk, protocol, port, name, scan_date \nFROM vulnerabilities\nWHERE ('$CVE_Filter' = 'All' or cve_id IN (${CVE_Filter:sqlstring})) \nAND\n('$Host_Filter' = 'All' or host IN (${Host_Filter:sqlstring}))\nAND\n('$Risk_Filter' = 'All' or risk IN (${Risk_Filter:sqlstring}))\nORDER BY \n  CASE WHEN risk = 'Critical' THEN 1\n       WHEN risk = 'High' THEN 2\n       WHEN risk = 'Medium' THEN 3\n       WHEN risk = 'Low' THEN 4\n       ELSE 5\n  END,\n  host, port",
     "rawQueryText": "SELECT cve_id, host, risk, protocol, port, name, scan_date \nFROM vulnerabilities\nWHERE ('$CVE_Filter' = 'All' or cve_id IN (${CVE_Filter:sqlstring})) \nAND\n('$Host_Filter' = 'All' or host IN (${Host_Filter:sqlstring}))\nAND\n('$Risk_Filter' = 'All' or risk IN (${Risk_Filter:sqlstring}))\nORDER BY \n  CASE WHEN risk = 'Critical' THEN 1\n       WHEN risk = 'High' THEN 2\n       WHEN risk = 'Medium' THEN 3\n       WHEN risk = 'Low' THEN 4\n       ELSE 5\n  END,\n  host, port",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Vulnerability Count by Severity",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT scan_date, critical_count, high_count, medium_count, low_count \nFROM scan_summary\n",
     "rawQueryText": "SELECT scan_date, critical_count, high_count, medium_count, low_count \nFROM scan_summary\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "CVE's by Count",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "queryText": "SELECT cve_id,risk, COUNT(*) as count\r\nFROM vulnerabilities\r\nWHERE ('$CVE_Filter' = 'All' or cve_id IN (${CVE_Filter:sqlstring})) \r\nAND\r\n('$Host_Filter' = 'All' or host IN (${Host_Filter:sqlstring}))\r\nAND\r\n('$Risk_Filter' = 'All' or risk IN (${Risk_Filter:sqlstring}))\r\nGROUP BY cve_id\r\nORDER BY count DESC\r\nLIMIT 10",
     "rawQueryText": "SELECT cve_id,risk, COUNT(*) as count\r\nFROM vulnerabilities\r\nWHERE ('$CVE_Filter' = 'All' or cve_id IN (${CVE_Filter:sqlstring})) \r\nAND\r\n('$Host_Filter' = 'All' or host IN (${Host_Filter:sqlstring}))\r\nAND\r\n('$Risk_Filter' = 'All' or risk IN (${Risk_Filter:sqlstring}))\r\nGROUP BY cve_id\r\nORDER BY count DESC\r\nLIMIT 10",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Vulnerability Count by Date",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "queryText": "SELECT scan_date, \n       critical_count, \n       high_count, \n       medium_count, \n       low_count\nFROM scan_summary\nORDER BY scan_date",
     "rawQueryText": "SELECT scan_date, \n       critical_count, \n       high_count, \n       medium_count, \n       low_count\nFROM scan_summary\nORDER BY scan_date",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Host Vulnerability Details",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "queryText": "SELECT Host, COUNT(*) as count\nFROM vulnerabilities\nWHERE ('$CVE_Filter' = 'All' or cve_id IN (${CVE_Filter:sqlstring})) \nAND\n('$Host_Filter' = 'All' or host IN (${Host_Filter:sqlstring}))\nAND\n('$Risk_Filter' = 'All' or risk IN (${Risk_Filter:sqlstring}))\nGROUP BY Host, Risk\nORDER BY Host, CASE \n    WHEN Risk = 'Critical' THEN 1\n    WHEN Risk = 'High' THEN 2\n    WHEN Risk = 'Medium' THEN 3\n    WHEN Risk = 'Low' THEN 4\n    ELSE 5\nEND",
     "rawQueryText": "SELECT Host, COUNT(*) as count\nFROM vulnerabilities\nWHERE ('$CVE_Filter' = 'All' or cve_id IN (${CVE_Filter:sqlstring})) \nAND\n('$Host_Filter' = 'All' or host IN (${Host_Filter:sqlstring}))\nAND\n('$Risk_Filter' = 'All' or risk IN (${Risk_Filter:sqlstring}))\nGROUP BY Host, Risk\nORDER BY Host, CASE \n    WHEN Risk = 'Critical' THEN 1\n    WHEN Risk = 'High' THEN 2\n    WHEN Risk = 'Medium' THEN 3\n    WHEN Risk = 'Low' THEN 4\n    ELSE 5\nEND",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Top Protocols & Ports",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "queryText": "SELECT protocol, port, COUNT(*) as count\nFROM vulnerabilities\nWHERE ('$CVE_Filter' = 'All' or cve_id IN (${CVE_Filter:sqlstring})) \nAND\n('$Host_Filter' = 'All' or host IN (${Host_Filter:sqlstring}))\nAND\n('$Risk_Filter' = 'All' or risk IN (${Risk_Filter:sqlstring}))\nGROUP BY protocol, port\nORDER BY count DESC\nLIMIT 10",
     "rawQueryText": "SELECT protocol, port, COUNT(*) as count\nFROM vulnerabilities\nWHERE ('$CVE_Filter' = 'All' or cve_id IN (${CVE_Filter:sqlstring})) \nAND\n('$Host_Filter' = 'All' or host IN (${Host_Filter:sqlstring}))\nAND\n('$Risk_Filter' = 'All' or risk IN (${Risk_Filter:sqlstring}))\nGROUP BY protocol, port\nORDER BY count DESC\nLIMIT 10",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "New Devices",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "queryText": "SELECT ip_address, vulnerability_count \nFROM new_devices\nORDER BY scan_date DESC",
     "rawQueryText": "SELECT ip_address, vulnerability_count \nFROM new_devices\nORDER BY scan_date DESC",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}