# run.py
import os
import sys
import time
from datetime import datetime

# Get the base directory (project root)
BASE_DIR = os.path.dirname(os.path.abspath(__file__))

# Define data directories using absolute paths
RAW_DATA_DIR = os.path.join(BASE_DIR, 'data', 'raw')
PROCESSED_DATA_DIR = os.path.join(BASE_DIR, 'data', 'processed')
LOG_DIR = os.path.join(BASE_DIR, 'logs')

# Copy these values to a temporary config file right in the scripts dir
CONFIG_CONTENT = f"""
# Temporary config file generated by run.py
# Nessus settings
NESSUS_URL = 'https://192.168.50.188:8834'  # Update with your Nessus server IP
ACCESS_KEY = 'your_access_key'  # Update with your actual access key
SECRET_KEY = 'your_secret_key'  # Update with your actual secret key

# Directory paths
RAW_DATA_DIR = '{RAW_DATA_DIR.replace('\\', '/')}'
PROCESSED_DATA_DIR = '{PROCESSED_DATA_DIR.replace('\\', '/')}'
LOG_DIR = '{LOG_DIR.replace('\\', '/')}'

# Email settings
SMTP_SERVER = 'smtp.example.com'  # Update with your SMTP server
SMTP_PORT = 587  # Common port for TLS
SMTP_USER = 'your_email@example.com'
SMTP_PASSWORD = 'your_email_password'
DEFAULT_SENDER = 'nessus-alerts@example.com'
DEFAULT_RECIPIENTS = ['admin@example.com', 'security@example.com']

# Alert thresholds (# of vulnerabilities that trigger an alert)
ALERT_THRESHOLDS = {{
    'Critical': 0,  # Any critical vulnerability triggers an alert
    'High': 5,      # 5 or more high vulnerabilities trigger an alert
    'Medium': 10,   # 10 or more medium vulnerabilities trigger an alert
    'Low': 20       # 20 or more low vulnerabilities trigger an alert
}}

# Database settings for Grafana
DB_DIR = '{os.path.join(BASE_DIR, 'data', 'db').replace('\\', '/')}'
DB_PATH = '{os.path.join(BASE_DIR, 'data', 'db', 'vulnerability_data.db').replace('\\', '/')}'
"""

# Write temporary config directly to scripts directory
with open(os.path.join(BASE_DIR, 'scripts', 'config.py'), 'w') as f:
    f.write(CONFIG_CONTENT)

# Add scripts directory to path
scripts_dir = os.path.join(BASE_DIR, 'scripts')
sys.path.append(scripts_dir)

# Import scripts
import vulnerability_aggregator
import dashboard_connector

def run_full_process():
    """Run the full vulnerability management process"""
    timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    print(f"\n=== Starting vulnerability management process at {timestamp} ===\n")
    
    # Skip Nessus download for now and just process existing files
    
    # Step 1: Aggregate vulnerability data
    print("\n--- Step 1: Aggregating vulnerability data ---")
    if vulnerability_aggregator.aggregate_vulnerability_data():
        print("Data aggregation successful")
        
        # Step 2: Update dashboard data
        print("\n--- Step 2: Updating dashboard data ---")
        if dashboard_connector.update_database():
            print("Dashboard data update successful")
        else:
            print("Dashboard data update failed")
    else:
        print("Data aggregation failed")
    
    print(f"\n=== Vulnerability management process completed at {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} ===\n")

if __name__ == "__main__":
    # Create required directories
    os.makedirs(RAW_DATA_DIR, exist_ok=True)
    os.makedirs(PROCESSED_DATA_DIR, exist_ok=True)
    os.makedirs(LOG_DIR, exist_ok=True)
    os.makedirs(os.path.join(BASE_DIR, 'data', 'db'), exist_ok=True)
    
    # Run process
    run_full_process()
