
# Temporary config file generated by run.py
# Nessus settings
NESSUS_URL = 'https://192.168.50.188:8834'  # Update with your Nessus server IP
ACCESS_KEY = 'your_access_key'  # Update with your actual access key
SECRET_KEY = 'your_secret_key'  # Update with your actual secret key

# Directory paths
RAW_DATA_DIR = 'C:/Users/brist/OneDrive/Documents/uniti_vulnerability_system/data/raw'
PROCESSED_DATA_DIR = 'C:/Users/brist/OneDrive/Documents/uniti_vulnerability_system/data/processed'
LOG_DIR = 'C:/Users/brist/OneDrive/Documents/uniti_vulnerability_system/logs'

# Email settings
SMTP_SERVER = 'smtp.example.com'  # Update with your SMTP server
SMTP_PORT = 587  # Common port for TLS
SMTP_USER = 'your_email@example.com'
SMTP_PASSWORD = 'your_email_password'
DEFAULT_SENDER = 'nessus-alerts@example.com'
DEFAULT_RECIPIENTS = ['admin@example.com', 'security@example.com']

# Alert thresholds (# of vulnerabilities that trigger an alert)
ALERT_THRESHOLDS = {
    'Critical': 0,  # Any critical vulnerability triggers an alert
    'High': 5,      # 5 or more high vulnerabilities trigger an alert
    'Medium': 10,   # 10 or more medium vulnerabilities trigger an alert
    'Low': 20       # 20 or more low vulnerabilities trigger an alert
}

# Database settings for Grafana
DB_DIR = 'C:/Users/brist/OneDrive/Documents/uniti_vulnerability_system/data/db'
DB_PATH = 'C:/Users/brist/OneDrive/Documents/uniti_vulnerability_system/data/db/vulnerability_data.db'
